# Generated by Django 4.2 on 2023-08-24 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_area_datecreate_area_dateupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='dateCreate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='dateUpdate',
            field=models.DateField(auto_now=True),
        ),
    ]
