# Generated by Django 4.2 on 2023-08-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_work_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='detail',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
