# Generated by Django 4.2 on 2023-09-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_work_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.area'),
        ),
        migrations.AddField(
            model_name='work',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.equipment'),
        ),
        migrations.AddField(
            model_name='work',
            name='stopage_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='stoppage',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='todo_later',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='dateCreate',
            field=models.DateField(auto_now=True),
        ),
    ]
