# Generated by Django 4.2 on 2023-09-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_work_area_work_equipment_work_stopage_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='area',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('dateUpdate', models.DateField(auto_now=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.area')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.location'),
        ),
    ]
