# Generated by Django 4.2 on 2023-09-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_work_area_location_work_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='stoppage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='todo_later',
            field=models.BooleanField(default=False),
        ),
    ]
