# Generated by Django 4.2 on 2023-09-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_work_stoppage_alter_work_todo_later'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='location',
        ),
        migrations.AddField(
            model_name='work',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.area'),
        ),
    ]
