# Generated by Django 4.2 on 2023-09-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_work_location_work_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.location'),
        ),
    ]
